name: Run "make" and "make install"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
    build:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: isntall dependencies
        run: sudo apt-get update && sudo apt-get install -y make gcc

      - name: run make
        run: make

      - name: rum make install
        run: make install
