name: Run "make" and "make install"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: make
      run: make
    - name: make check
      run: make check  
    - name: make install
      run: make install
